version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "443:443"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./certs:/app/certs:ro
    environment:
      - NODE_ENV=development
      - HTTPS=true
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - backend
    networks:
      - app-network
    hostname: frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./database:/app/database
      - ./certs:/app/certs:ro
    environment:
      - NODE_ENV=development
      - DATABASE_URL=sqlite:/app/database/db.sqlite
      - HTTPS=true
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    networks:
      - app-network
    hostname: backend

networks:
  app-network:
    driver: bridge