version: '3.8'

services:
  dev42:
    build: .
    container_name: 42dev
    volumes:
      - ..:/home/dev42/inception
      - dev42_docker:/home/dev42/.docker
    environment:
      - DOCKER_HOST=unix:///home/dev42/.docker/run/docker.sock
    privileged: true  # Needed for Docker-in-Docker
    ports:
      - "8443:8443"  # Map the non-privileged port
    command: >
      bash -c "
        dockerd-rootless.sh &
        sleep 5 &&
        bash"

volumes:
  dev42_docker: # For persisting Docker daemon files 