# Service Definitions
services:
  # NGINX Service - SSL Termination & Reverse Proxy
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: ${RESTART_POLICY}
    ports:
      - "443:443"  # HTTPS only - TLSv1.2/1.3
    volumes:
      - wordpress_data:/var/www/html  # WordPress files
    networks:
      - inception_network
    depends_on:
      - wordpress  # Ensures WordPress is ready before NGINX starts

  # MariaDB Service - Database Backend
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: ${RESTART_POLICY}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql  # Persistent database storage
    networks:
      - inception_network
    secrets:  # Secure credentials management
      - source: db_root_password
        target: /run/secrets/db_root_password
      - source: db_password
        target: /run/secrets/db_password

  # WordPress Service - PHP-FPM Application
  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: ${RESTART_POLICY}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    volumes:
      - wordpress_data:/var/www/html  # WordPress files
    networks:
      - inception_network
    secrets:  # Secure credentials management
      - source: db_password
        target: /run/secrets/db_password
      - source: wp_admin_password
        target: /run/secrets/wp_admin_password
      - source: wp_user_password
        target: /run/secrets/wp_user_password
    depends_on:
      - mariadb

# Network Configuration
networks:
  inception_network:
    name: ${NETWORK_NAME}
    driver: bridge  # Isolated network for inter-container communication

# Secrets Management
secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

# Volume Configuration - Using named volumes
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/mariadb
